const KEY='prehab-v1';
const defaultState={weight:88,target:82,trainings:[]};
let state=JSON.parse(localStorage.getItem(KEY)||'null')||defaultState;
const activities=[['🚴','Radfahren','Ausdauer'],['🏊','Schwimmen','Ausdauer'],['💪','Bändertraining','Kraft'],['🌀','Faszienrolle','Mobilität'],['🧘','Dehnen','Mobilität'],['🎾','Tennis','Sport']];
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function resetDevData(){if(confirm('Alle lokalen Entwicklungsdaten wirklich zurücksetzen?')){localStorage.removeItem(KEY);state={...defaultState,trainings:[]};showPage('home')}}
function devReset(){return `<div class="dev-reset"><button onclick="resetDevData()">Entwicklungsdaten zurücksetzen</button></div>`}
function updateClock(){const n=new Date();document.getElementById('todayDate').textContent=n.toLocaleDateString('de-DE',{weekday:'long',day:'2-digit',month:'long'});document.getElementById('todayTime').textContent=n.toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})}
setInterval(updateClock,1000);updateClock();
function daysToOp(){return Math.max(0,Math.ceil((new Date('2026-10-15T00:00:00')-new Date())/86400000))}
function progress(){return Math.max(0,Math.min(100,((88-state.weight)/(88-state.target))*100))}
function showPage(page){document.querySelectorAll('.tabbar button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));const c=document.getElementById('content');if(page==='home')home(c);if(page==='training')training(c);if(page==='history')history(c);if(page==='stats')stats(c)}
function home(c){const today=new Date().toISOString().slice(0,10),ts=state.trainings.filter(x=>x.date===today);c.innerHTML=`<div class="page"><section class="hero"><div class="small">DEIN AKTUELLER STAND</div><div class="weight">${state.weight.toFixed(1)} kg</div><div class="goal">Zielgewicht ${state.target.toFixed(1)} kg</div><div class="bar"><i style="width:${progress()}%"></i></div><div class="countdown">🏥 Noch <b>${daysToOp()}</b> Tage bis zur OP · 15.10.2026</div></section><div class="section-title">Heute</div>${ts.length?ts.map(card).join(''):'<div class="card empty">Noch kein Training eingetragen.<br>Heute ist ein guter Tag zum Start.</div>'}<button class="primary" onclick="openTraining()">＋ Training eintragen</button><div class="section-title">Gewicht</div><div class="card training-row" onclick="openWeight()"><div class="emoji">⚖️</div><div class="row-main"><strong>${state.weight.toFixed(1)} kg</strong><small>Letztes Gewicht · Ziel ${state.target} kg</small></div><div class="chev">›</div></div>${devReset()}</div>`}
function card(x){return `<div class="card training-row"><div class="emoji">${x.icon}</div><div class="row-main"><strong>${x.type}</strong><small>${x.duration} min · Intensität ${x.intensity}/10</small></div></div>`}
function training(c){c.innerHTML=`<div class="page"><div class="section-title">Training auswählen</div>${activities.map(a=>`<div class="card training-row" onclick="openTraining('${a[1]}')"><div class="emoji">${a[0]}</div><div class="row-main"><strong>${a[1]}</strong><small>${a[2]}</small></div><div class="chev">›</div></div>`).join('')}${devReset()}</div>`}
function history(c){const rows=[...state.trainings].reverse();c.innerHTML=`<div class="page"><div class="section-title">Trainingsverlauf</div>${rows.length?rows.map(x=>`<div class="card training-row"><div class="emoji">${x.icon}</div><div class="row-main"><strong>${x.type}</strong><small>${new Date(x.date).toLocaleDateString('de-DE')} · ${x.duration} min · ${x.intensity}/10</small></div></div>`).join(''):'<div class="card empty">Noch keine Trainings.</div>'}${devReset()}</div>`}
function stats(c){const mins=state.trainings.reduce((s,x)=>s+Number(x.duration),0);const sessions=state.trainings.length;c.innerHTML=`<div class="page"><div class="section-title">Dein Fortschritt</div><div class="grid"><div class="stat-card"><b>${state.weight.toFixed(1)}</b><small>kg aktuell</small></div><div class="stat-card"><b>${(88-state.weight).toFixed(1)}</b><small>kg verloren</small></div><div class="stat-card"><b>${sessions}</b><small>Trainings</small></div><div class="stat-card"><b>${mins}</b><small>Trainingsminuten</small></div></div><div class="section-title">Ziel</div><div class="card"><strong>${progress().toFixed(0)} %</strong> auf dem Weg von 88 kg zu 82 kg<div class="bar" style="background:#eee"><i style="width:${progress()}%"></i></div></div>${devReset()}</div>`}
function openWeight(){modal(`<h2>Gewicht eintragen</h2><div class="field"><label>Gewicht in kg</label><input id="w" type="number" step="0.1" value="${state.weight}"></div><button class="primary" onclick="state.weight=Number(document.getElementById('w').value);save();closeModal();showPage('home')">Speichern</button>`)}
function openTraining(type='Radfahren'){const opts=activities.map(a=>`<option ${a[1]===type?'selected':''}>${a[1]}</option>`).join('');const icon=t=>activities.find(a=>a[1]===t)?.[0]||'🏃';modal(`<h2>Training eintragen</h2><div class="field"><label>Aktivität</label><select id="t">${opts}</select></div><div class="field"><label>Dauer in Minuten</label><input id="d" type="number" value="45" min="1"></div><div class="field"><label>Intensität · 1–10</label><input id="i" type="number" value="5" min="1" max="10"></div><button class="primary" onclick="const t=document.getElementById('t').value;state.trainings.push({date:new Date().toISOString().slice(0,10),type:t,icon:icon(t),duration:Number(document.getElementById('d').value),intensity:Number(document.getElementById('i').value)});save();closeModal();showPage('home')">Training speichern</button>`)}
function modal(html){document.getElementById('modal').innerHTML=`<div class="sheet">${html}<button style="width:100%;padding:14px;background:none;color:#777" onclick="closeModal()">Abbrechen</button></div>`;document.getElementById('modal').classList.remove('hidden')}
function closeModal(){document.getElementById('modal').classList.add('hidden')}
showPage('home');