const KEY='prehab-v1';
const defaultState={weight:88,target:82,trainings:[],checks:{}};let state=JSON.parse(localStorage.getItem(KEY)||'null')||defaultState;if(!state.checks)state.checks={};
const activities=[['🚴','Radfahren','Ausdauer'],['🏊','Schwimmen','Ausdauer'],['💪','Bändertraining','Kraft'],['🌀','Faszienrolle','Mobilität'],['🧘','Dehnen','Mobilität'],['🤸','Mobilitätsübungen','Mobilität'],['🎾','Tennis','spontan']];
const week=[
{title:'Kraft A · Hüfte & Rumpf',icon:'🦵',time:'35–40 min',items:['Glute Bridge · 3 × 10–15','Hüftabduktion mit Band · 3 × 10–15 je Seite','Stehende Hüftextension mit Band · 3 × 10–15','Sit-to-Stand · 3 × 8–12','Wadenheben · 3 × 15','Bird Dog · 3 × 8 je Seite','Dead Bug · 3 × 8 je Seite']},
{title:'Rad + Mobility',icon:'🚴',time:'55–70 min',items:['Radfahren locker–moderat · 45–60 min','Mobilitätsübungen · 10 min']},
{title:'Kraft B · Oberkörper & Rumpf',icon:'💪',time:'35 min',items:['Rudern mit Band · 3 × 12–15','Brustdrücken mit Band · 3 × 10–15','Schulterdrücken · 3 × 10–12','Trizepsdrücken mit Band · 3 × 12–15','Bizeps-Curls · 3 × 12–15','Pallof Press · 3 × 10 je Seite','Unterarmstütz · 3 × 20–40 s']},
{title:'Schwimmen + Dehnen',icon:'🏊',time:'40–55 min',items:['Schwimmen locker–moderat · 30–45 min','Leichtes Dehnen · 10 min']},
{title:'Kraft C · Ganzkörper Prehab',icon:'🏋️',time:'40 min',items:['Sit-to-Stand · 3 × 10','Niedrige Step-ups · 3 × 8 je Seite','Seitliche Schritte mit Band · 3 × 8–12 je Richtung','Glute Bridge · 3 × 12','Rudern mit Band · 3 × 12','Trizepsdrücken · 3 × 12','Pallof Press · 3 × 10','Bird Dog · 3 × 8']},
{title:'Lange Ausdauer',icon:'🚴',time:'60–90 min',items:['Radfahren locker–moderat · 60–90 min','Optional 5–10 min lockere Mobility']},
{title:'Regeneration',icon:'🧘',time:'20–30 min',items:['Mobilitätsübungen · 10–15 min','Faszienrolle · 10 min','Leichtes Dehnen · 5 min']}
];
function save(){localStorage.setItem(KEY,JSON.stringify(state))}function keyDate(){return new Date().toLocaleDateString('sv-SE')}function resetDevData(){if(confirm('Alle lokalen Entwicklungsdaten wirklich zurücksetzen?')){localStorage.removeItem(KEY);state={...defaultState,trainings:[],checks:{}};showPage('home')}}function devReset(){return `<div class="dev-reset"><button onclick="resetDevData()">Entwicklungsdaten zurücksetzen</button></div>`}
function updateClock(){const n=new Date();todayDate.textContent=n.toLocaleDateString('de-DE',{weekday:'long',day:'2-digit',month:'long'});todayTime.textContent=n.toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})}setInterval(updateClock,1000);updateClock();
function daysToOp(){return Math.max(0,Math.ceil((new Date('2026-10-15')-new Date())/86400000))}function progress(){return Math.max(0,Math.min(100,((88-state.weight)/(88-state.target))*100))}
function phase(){const n=new Date();if(n<new Date('2026-08-31'))return 'Einstieg';if(n<new Date('2026-09-28'))return 'Aufbau';if(n<new Date('2026-10-12'))return 'Fitness halten';return 'Taper'}
function todayPlan(){return week[(new Date().getDay()+6)%7]}
function showPage(p){document.querySelectorAll('.tabbar button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));const c=content;if(p==='home')home(c);if(p==='plan')plan(c);if(p==='training')training(c);if(p==='history')history(c);if(p==='stats')stats(c)}
function planCard(x,full=false){return `<div class="card"><div class="training-row"><div class="emoji">${x.icon}</div><div class="row-main"><strong>${x.title}</strong><small>${x.time} · Phase ${phase()}</small></div></div>${full?`<div style="margin-top:14px">${x.items.map((it,i)=>{let k=keyDate()+'-'+i,done=!!state.checks[k];return `<div style="display:flex;gap:10px;padding:10px 0;border-top:1px solid #eee;align-items:center"><input type="checkbox" ${done?'checked':''} onchange="state.checks['${k}']=this.checked;save()" style="width:22px;height:22px"><span>${it}</span></div>`}).join('')}</div>`:''}</div>`}
function home(c){let x=todayPlan(),ts=state.trainings.filter(t=>t.date===keyDate());c.innerHTML=`<div class="page"><section class="hero"><div class="small">DEIN AKTUELLER STAND · ${phase().toUpperCase()}</div><div class="weight">${state.weight.toFixed(1)} kg</div><div class="goal">Zielgewicht ${state.target.toFixed(1)} kg</div><div class="bar"><i style="width:${progress()}%"></i></div><div class="countdown">🏥 Noch <b>${daysToOp()}</b> Tage bis zur OP · 15.10.2026</div></section><div class="section-title">Dein Training heute</div>${planCard(x)}<button class="primary" onclick="showPage('plan')">Training ansehen</button>${ts.length?`<div class="section-title">Heute eingetragen</div>${ts.map(card).join('')}`:''}<div class="section-title">Gewicht</div><div class="card training-row" onclick="openWeight()"><div class="emoji">⚖️</div><div class="row-main"><strong>${state.weight.toFixed(1)} kg</strong><small>Ziel ${state.target} kg</small></div><div class="chev">›</div></div>${devReset()}</div>`}
function plan(c){let x=todayPlan();c.innerHTML=`<div class="page"><div class="section-title">Heute · ${phase()}</div>${planCard(x,true)}<div class="section-title">7-Tage-Plan</div>${week.map((w,i)=>`<div class="card training-row"><div class="emoji">${w.icon}</div><div class="row-main"><strong>${['Mo','Di','Mi','Do','Fr','Sa','So'][i]} · ${w.title}</strong><small>${w.time}</small></div></div>`).join('')}<div class="card"><small>Tennis ist bewusst nicht eingeplant. Spontane Tennis-Einheiten kannst du unter Training erfassen. Bei deutlichen Hüftschmerzen eine Übung abbrechen und medizinische/physiotherapeutische Vorgaben haben Vorrang.</small></div>${devReset()}</div>`}
function card(x){return `<div class="card training-row"><div class="emoji">${x.icon}</div><div class="row-main"><strong>${x.type}</strong><small>${x.duration} min · Intensität ${x.intensity}/10</small></div></div>`}
function training(c){c.innerHTML=`<div class="page"><div class="section-title">Training spontan eintragen</div>${activities.map(a=>`<div class="card training-row" onclick="openTraining('${a[1]}')"><div class="emoji">${a[0]}</div><div class="row-main"><strong>${a[1]}</strong><small>${a[2]}</small></div><div class="chev">›</div></div>`).join('')}${devReset()}</div>`}
function history(c){let rows=[...state.trainings].reverse();c.innerHTML=`<div class="page"><div class="section-title">Trainingsverlauf</div>${rows.length?rows.map(card).join(''):'<div class="card empty">Noch keine Trainings.</div>'}${devReset()}</div>`}
function stats(c){let mins=state.trainings.reduce((s,x)=>s+Number(x.duration),0);c.innerHTML=`<div class="page"><div class="section-title">Dein Fortschritt</div><div class="grid"><div class="stat-card"><b>${state.weight.toFixed(1)}</b><small>kg aktuell</small></div><div class="stat-card"><b>${(88-state.weight).toFixed(1)}</b><small>kg verloren</small></div><div class="stat-card"><b>${state.trainings.length}</b><small>Trainings</small></div><div class="stat-card"><b>${mins}</b><small>Trainingsminuten</small></div></div><div class="section-title">Aktuelle Phase</div><div class="card"><strong>${phase()}</strong><br><small>Trainingssteuerung bis zur OP am 15.10.2026</small></div>${devReset()}</div>`}
function openWeight(){modal(`<h2>Gewicht eintragen</h2><div class="field"><label>Gewicht in kg</label><input id="w" type="number" step="0.1" value="${state.weight}"></div><button class="primary" onclick="state.weight=Number(w.value);save();closeModal();showPage('home')">Speichern</button>`)}
function openTraining(type='Radfahren'){let opts=activities.map(a=>`<option ${a[1]===type?'selected':''}>${a[1]}</option>`).join('');let icon=t=>activities.find(a=>a[1]===t)?.[0]||'🏃';modal(`<h2>Training eintragen</h2><div class="field"><label>Aktivität</label><select id="t">${opts}</select></div><div class="field"><label>Dauer in Minuten</label><input id="d" type="number" value="45"></div><div class="field"><label>Intensität · 1–10</label><input id="i" type="number" value="5" min="1" max="10"></div><button class="primary" onclick="let v=t.value;state.trainings.push({date:keyDate(),type:v,icon:icon(v),duration:Number(d.value),intensity:Number(i.value)});save();closeModal();showPage('home')">Training speichern</button>`)}
function modal(h){modalEl=document.getElementById('modal');modalEl.innerHTML=`<div class="sheet">${h}<button style="width:100%;padding:14px;background:none;color:#777" onclick="closeModal()">Abbrechen</button></div>`;modalEl.classList.remove('hidden')}function closeModal(){document.getElementById('modal').classList.add('hidden')}showPage('home');