(()=>{
const BUILD='v0.8.0 · Build 20260813-18';
const cfg=window.PREHIP_SUPABASE_CONFIG;
let client=null,user=null,localSave=null,baseHome=null,syncTimer=null,syncing=false,cloudReady=false,lastError='',loadedOnce=false;
const setVersion=()=>{const v=document.querySelector('.version');if(v)v.textContent=BUILD};
function normalize(raw){const d=raw&&typeof raw==='object'?raw:{};return {...state,...d,trainings:Array.isArray(d.trainings)?d.trainings:[],checks:d.checks&&typeof d.checks==='object'?d.checks:{},completed:Array.isArray(d.completed)?d.completed:[],weightHistory:Array.isArray(d.weightHistory)?d.weightHistory:[]}}
async function readCloud(){if(!client||!user)return null;const {data,error}=await client.from('app_state').select('state,updated_at').eq('user_id',user.id).maybeSingle();if(error)throw error;return data||null}
async function writeCloud(force=false){if(!client||!user||syncing||(!cloudReady&&!force))return;syncing=true;lastError='';decorateCloud();try{const {error}=await client.from('app_state').upsert({user_id:user.id,state:state,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error)throw error;cloudReady=true}catch(e){lastError=e.message||String(e)}finally{syncing=false;decorateCloud()}}
function scheduleCloud(){if(!user||!cloudReady)return;clearTimeout(syncTimer);syncTimer=setTimeout(()=>writeCloud(),700)}
async function loadForSession(session){setVersion();user=session?.user||null;if(!user){cloudReady=false;loadedOnce=false;decorateCloud();return}try{const remote=await readCloud();if(remote?.state){state=normalize(remote.state);localSave();cloudReady=true;loadedOnce=true;showPage(document.querySelector('.tabbar button.active')?.dataset.page||'home')}else{cloudReady=true;loadedOnce=true;await writeCloud(true)}lastError=''}catch(e){lastError=e.message||String(e);cloudReady=false}decorateCloud()}
function cloudStatus(){if(user&&cloudReady)return {icon:'☁️',title:'Supabase Cloud aktiv',sub:user.email||'Angemeldet'};if(user&&lastError)return {icon:'⚠️',title:'Cloud-Sync Fehler',sub:lastError};if(user)return {icon:'☁️',title:'Cloud wird verbunden …',sub:user.email||''};return {icon:'🔐',title:'Cloud anmelden',sub:'Daten bleiben auch nach Cache-Löschen erhalten'}}
function cloudCard(){const s=cloudStatus();return `<div class="section-title">Cloud</div><div class="card training-row" onclick="openPrehipCloud()"><div class="emoji">${s.icon}</div><div class="row-main"><strong>${s.title}</strong><small>${s.sub}</small></div><div class="chev">›</div></div>`}
function decorateCloud(){const holder=document.getElementById('prehip-cloud-card');if(holder)holder.innerHTML=cloudCard()}
function msg(text,error=false){const el=document.getElementById('cloud-msg');if(el){el.textContent=text;el.style.color=error?'#b42318':'#667085'}}
window.openPrehipCloud=function(){if(user){modal(`<h2>preHIP Cloud</h2><div class="card" style="margin:0 0 12px"><strong>☁️ Synchronisiert</strong><br><small>${user.email||''}</small></div><p style="font-size:13px;color:#666;line-height:1.45">Training, Verlauf, Gewicht und Einstellungen werden in Supabase gespeichert. Lokal bleibt zusätzlich ein Offline-Cache.</p><div id="cloud-msg" style="min-height:18px;font-size:12px;margin:8px 0"></div><button class="primary" onclick="prehipCloudSyncNow()">Jetzt synchronisieren</button><button style="width:100%;padding:13px;margin-top:8px;border-radius:12px;background:#f2f2ef;font-weight:700" onclick="prehipCloudReload()">Cloud-Daten neu laden</button><button style="width:100%;padding:13px;margin-top:8px;background:none;color:#b42318" onclick="prehipCloudSignOut()">Auf diesem Gerät abmelden</button>`)}else{modal(`<h2>preHIP Cloud</h2><p style="font-size:13px;color:#666;line-height:1.45">Melde dich per E-Mail an. Du bekommst einen Magic Link. Beim ersten Login werden deine bisherigen lokalen Daten automatisch in die Cloud übernommen.</p><div class="field"><label>E-Mail</label><input id="cloud-email" type="email" inputmode="email" autocomplete="email" placeholder="name@beispiel.de"></div><div id="cloud-msg" style="min-height:18px;font-size:12px;margin:8px 0"></div><button class="primary" onclick="prehipCloudMagicLink()">Magic Link senden</button>`)}}
window.prehipCloudMagicLink=async function(){const email=document.getElementById('cloud-email')?.value.trim();if(!email){msg('Bitte E-Mail-Adresse eingeben.',true);return}msg('Magic Link wird gesendet …');const redirect=`${location.origin}${location.pathname}`;const {error}=await client.auth.signInWithOtp({email,options:{emailRedirectTo:redirect}});if(error){msg(error.message,true);return}msg('E-Mail ist unterwegs. Öffne den Link auf diesem iPhone.')}
window.prehipCloudSyncNow=async()=>{msg('Synchronisiere …');await writeCloud(true);msg(lastError||'Cloud ist aktuell.',!!lastError)};
window.prehipCloudReload=async()=>{msg('Lade Cloud-Daten …');try{const remote=await readCloud();if(remote?.state){state=normalize(remote.state);localSave();showPage('home');closeModal()}else msg('Noch keine Cloud-Daten vorhanden.',true)}catch(e){msg(e.message||String(e),true)}};
window.prehipCloudSignOut=async()=>{await client.auth.signOut({scope:'local'});user=null;cloudReady=false;closeModal();showPage('home')};
function init(){setVersion();if(!cfg||!window.supabase||typeof state==='undefined'||typeof save!=='function'||typeof home!=='function'||typeof modal!=='function'){setTimeout(init,100);return}
 client=window.supabase.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
 localSave=save;save=function(){localSave();scheduleCloud()};
 baseHome=home;home=function(c){baseHome(c);const page=c.querySelector('.page');if(page){const holder=document.createElement('div');holder.id='prehip-cloud-card';holder.innerHTML=cloudCard();const reset=page.querySelector('.dev-reset');if(reset)page.insertBefore(holder,reset);else page.appendChild(holder)}};
 client.auth.onAuthStateChange((event,session)=>{setTimeout(()=>loadForSession(session),0)});
 client.auth.getSession().then(({data})=>loadForSession(data.session));
 window.addEventListener('online',()=>{if(user)writeCloud(true)});
 showPage('home');setVersion();
}
init();
})();