const APP_VERSION='v1.0.0-beta.1';
const BUILD='20260813-2332';
const KEY='prehab-v1';
const START_WEIGHT=88;
const DEFAULT_OP_DATE='2026-10-15';
const PLAN_START=new Date('2026-08-16T12:00:00');
const ROTATION_START=new Date('2026-08-17T12:00:00');
const state0={
  weight:88,target:82,trainings:[],checks:{},completed:[],weightHistory:[],workoutSessions:[],feelings:{},appointments:[],
  profile:{onboardingDone:false,opDate:DEFAULT_OP_DATE,goals:['Aktiver Alltag','Radfahren','Schwimmen','Fitness'],activityLevel:'Aktiv',equipment:['Theraband','Fahrrad','Rudergerät'],trainingDays:[1,2,3,5,6,0]}
};
let stored=null;try{stored=JSON.parse(localStorage.getItem(KEY)||'null')}catch(e){}
let state={...state0,...(stored||{})};
state.profile={...state0.profile,...(state.profile||{})};
if(!Array.isArray(state.trainings))state.trainings=[];
if(!state.checks||typeof state.checks!=='object')state.checks={};
if(!Array.isArray(state.completed))state.completed=[];
if(!Array.isArray(state.weightHistory))state.weightHistory=[];
if(!Array.isArray(state.workoutSessions))state.workoutSessions=[];
if(!state.feelings||typeof state.feelings!=='object')state.feelings={};
if(!Array.isArray(state.appointments))state.appointments=[];
if(!Array.isArray(state.profile.goals))state.profile.goals=[];
if(!Array.isArray(state.profile.equipment))state.profile.equipment=[];
if(!Array.isArray(state.profile.trainingDays))state.profile.trainingDays=[1,2,3,5,6,0];
if(!state.weightHistory.length)state.weightHistory=[{date:dayKey(new Date()),weight:Number(state.weight)||START_WEIGHT}];

const W='https://commons.wikimedia.org/wiki/Special:FilePath/';
const webImg={bridge:['Bridge-1.png','Everkinetic · CC BY-SA 3.0'],bird:['Bird dog exercise.jpg','Wikimedia Commons'],rowband:['Upright band rows 1.svg','Everkinetic · CC BY-SA 3.0'],chestpress:['Incline bench press with bands 1.svg','Everkinetic · CC BY-SA 3.0'],triceps:['Standing triceps extension 1.svg','Everkinetic · CC BY-SA 3.0'],plank:['Plank exercise.svg','Wikimedia Commons'],step:['Step-ups-2-801x1024.png','Everkinetic · CC BY-SA 3.0'],bike:['Stationary bikes at a gym.jpg','KeepActive Australia · CC BY-SA 4.0'],rower:['Concept 2 Indoor Rowers.JPG','Public Domain']};
const videos={'Glute Bridge':'Z3cY3d3BBo4','Bird Dog':'ZdAHe9_HeEw','Dead Bug':'bxn9FBrt4-A','Unterarmstütz':'mwlp75MS6Rg','Pallof Press':'axgv7H_VQOo','Rudergerät locker–moderat':'4zWu1yuJ0_g','Einrudern':'4zWu1yuJ0_g','Ausrudern':'4zWu1yuJ0_g','Brustdrücken mit Band':'_x5m-s8xTf0','Hüftbeuger dehnen':'IzHUoWs0maQ','Hüftbeuger mobilisieren':'IzHUoWs0maQ','Gesäß mobilisieren':'IzHUoWs0maQ','Rudern mit Band':'_x5m-s8xTf0','Trizepsdrücken mit Band':'WDIpL0pjun0','Sit-to-Stand':'WDIpL0pjun0','Niedrige Step-ups':'WDIpL0pjun0','Seitliche Schritte mit Band':'AJF5PCNz9Ls','Hüftabduktion mit Band':'IzHUoWs0maQ','Stehende Hüftextension mit Band':'Z3cY3d3BBo4','Hintere Oberschenkel dehnen':'83G00Fwlqqw'};
const activities=[['🚶','Spaziergang','Alltag'],['🚴','Radfahren','Ausdauer'],['🚣','Rudergerät','Ausdauer'],['🏊','Schwimmen','Ausdauer'],['💪','Krafttraining','Kraft'],['🧘','Mobilität','Mobilität'],['🎾','Tennis','Spontan'],['＋','Sonstiges','Aktivität']];
const E=(name,dose,target,desc,media='zip:hip')=>({name,dose,target,desc,media});
const REST={id:'rest',title:'Kompletter Ruhetag',short:'Ruhetag',icon:'☁️',time:'Erholung',rest:true,items:[]};
const PRESTART={id:'prestart',title:'Trainingsstart am 16.08.',short:'Vorbereitung',icon:'🗓️',time:'Noch kein Pflichttraining',rest:true,items:[]};
const HIP_A={id:'hip-a',title:'Hüfte & Rumpf A',short:'Kraft A',icon:'🦵',time:'35–40 min',items:[E('Glute Bridge','3 × 10–15','Gesäß · Beckenstabilität','Becken kontrolliert anheben, oben kurz das Gesäß anspannen.','bridge'),E('Hüftabduktion mit Band','3 × 10–15 je Seite','Seitliches Gesäß · Hüftstabilität','Aufrecht stehen, Bein langsam seitlich führen, Becken bleibt ruhig.','zip:glute'),E('Sit-to-Stand','3 × 8–12','Quadrizeps · Gesäß · Aufstehen','Von einem stabilen Stuhl kontrolliert aufstehen und langsam wieder absetzen.','zip:quad'),E('Niedrige Step-ups','3 × 8 je Seite','Quadrizeps · Gesäß · Treppenfunktion','Niedrige Stufe, Fuß ganz aufsetzen und stabil hochdrücken.','step'),E('Dead Bug','3 × 8 je Seite','Rumpf · Beckenstabilität','Lendenwirbelsäule stabil halten und diagonal Arm und Bein absenken.','plank')]};
const HIP_B={id:'hip-b',title:'Hüfte & Funktion B',short:'Kraft B',icon:'🏋️',time:'35–40 min',items:[E('Stehende Hüftextension mit Band','3 × 10–15 je Seite','Gesäß · Hüftstreckung','Bein kontrolliert nach hinten führen, ohne ins Hohlkreuz zu gehen.','zip:glute'),E('Seitliche Schritte mit Band','3 × 8–12 je Richtung','Seitliches Gesäß · Hüftstabilität','Kleine kontrollierte Schritte, Knie und Füße zeigen nach vorn.','zip:glute'),E('Sit-to-Stand','3 × 10','Quadrizeps · Gesäß · Alltag','Kontrolliert aufstehen und wieder hinsetzen.','zip:quad'),E('Glute Bridge','3 × 12','Gesäß · Beckenstabilität','Becken anheben und kontrolliert wieder absenken.','bridge'),E('Bird Dog','3 × 8 je Seite','Rumpf · Rücken · Gesäß','Diagonal strecken, ohne das Becken zu verdrehen.','bird')]};
const BIKE_A={id:'bike-a',title:'Radfahren + Hüftdehnung',short:'Rad + Dehnen',icon:'🚴',time:'55–70 min',items:[E('Einrollen','8 min','Kreislauf · Beine','Sehr locker beginnen und einen leichten Gang wählen.','bike'),E('Radfahren locker–moderat','35–50 min','Ausdauer · Beine','Gleichmäßig treten; du solltest noch in kurzen Sätzen sprechen können.','bike'),E('Ausrollen','7 min','Regeneration','Leichter Gang und ruhig ausfahren.','bike'),E('Hüftbeuger dehnen','2 × 30 s je Seite','Hüftbeuger','Becken sanft nach vorn schieben, nur angenehmer Zug.','zip:hip'),E('Hintere Oberschenkel dehnen','2 × 30 s je Seite','Hamstrings','Rücken lang halten und aus der Hüfte nach vorn neigen.','zip:hamstring')]};
const BIKE_B={id:'bike-b',title:'Radfahren + Mobility',short:'Rad + Mobility',icon:'🚴',time:'60–75 min',items:[E('Einrollen','10 min','Kreislauf · Beine','Sehr locker beginnen.','bike'),E('Radfahren locker–moderat','40–50 min','Ausdauer · Beine','Ruhige, gleichmäßige Trittfrequenz ohne Druckspitzen.','bike'),E('Ausrollen','8 min','Regeneration','Tempo deutlich reduzieren.','bike'),E('Gesäß mobilisieren','2 × 30 s je Seite','Gesäß · Außenrotatoren','Knöchel aufs andere Knie legen und Rücken lang halten.','zip:glute'),E('Hüftbeuger mobilisieren','2 × 30 s je Seite','Hüftbeuger','Nur in einen angenehmen Zug gehen, nicht in Gelenkschmerz.','zip:hip')]};
const ROW_A={id:'row-a',title:'Rudergerät + Oberkörper A',short:'Rudern + OK A',icon:'🚣',time:'40–50 min',items:[E('Einrudern','5 min','Kreislauf · Rücken · Beine','Locker beginnen und nur so weit nach vorn rollen, wie die Hüfte angenehm bleibt.','rower'),E('Rudergerät locker–moderat','20–30 min','Ausdauer · Rücken · Rumpf','Gleichmäßig rudern, keine maximale Hüftbeugung erzwingen.','rower'),E('Ausrudern','5 min','Regeneration','Tempo und Widerstand deutlich reduzieren.','rower'),E('Brustdrücken mit Band','3 × 10–15','Brust · Trizeps','Band kontrolliert nach vorn drücken, Schulter bleibt tief.','chestpress'),E('Trizepsdrücken mit Band','3 × 12–15','Trizeps · Stützfähigkeit','Oberarme ruhig halten und kontrolliert strecken.','triceps'),E('Pallof Press','3 × 10 je Seite','Rumpf · Anti-Rotation','Band nach vorn drücken und Verdrehung aktiv verhindern.','zip:chest')]};
const ROW_B={id:'row-b',title:'Rudergerät + Oberkörper B',short:'Rudern + OK B',icon:'🚣',time:'40–50 min',items:[E('Einrudern','5 min','Kreislauf · Rücken · Beine','Locker beginnen, Bewegungsradius der Hüfte angenehm halten.','rower'),E('Rudergerät locker–moderat','25–30 min','Ausdauer · Rücken · Rumpf','Flüssiger Rhythmus, nicht tief in die Catch-Position ziehen.','rower'),E('Ausrudern','5 min','Regeneration','Locker ausrudern.','rower'),E('Rudern mit Band','3 × 12','Oberer Rücken · Schulterblätter','Ellenbogen nach hinten führen und Schulterblätter zusammenziehen.','rowband'),E('Trizepsdrücken mit Band','3 × 12','Trizeps · Stützfähigkeit','Kontrolliert strecken, Schultern bleiben entspannt.','triceps'),E('Unterarmstütz','3 × 20–40 s','Rumpf · Schultergürtel','Körper als Linie halten und ruhig weiteratmen.','plank')]};
const START_DAY={...BIKE_A,id:'start-bike',title:'Trainingsstart · Rad + Dehnen',short:'Start · Rad'};
const variants=[[HIP_A,BIKE_A,ROW_A,REST,HIP_B,BIKE_B,ROW_B],[BIKE_B,HIP_B,ROW_A,BIKE_A,REST,HIP_A,ROW_B],[ROW_B,BIKE_A,REST,HIP_A,ROW_A,BIKE_B,HIP_B]];
let view={page:'home',weekOffset:0,calendarOffset:0,selectedDate:null,workout:null,onboardingStep:0,onboardingDraft:null};
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function dayKey(d){const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`}
function dateFromKey(k){const [y,m,d]=String(k).split('-').map(Number);return new Date(y,m-1,d,12,0,0,0)}
function addDays(d,n){const x=new Date(d);x.setHours(12,0,0,0);x.setDate(x.getDate()+n);return x}
function startOfWeek(d=new Date()){const x=new Date(d);x.setHours(12,0,0,0);const delta=(x.getDay()+6)%7;x.setDate(x.getDate()-delta);return x}
function opDate(){return dateFromKey(state.profile.opDate||DEFAULT_OP_DATE)}
function signedDaysToOp(){const today=dateFromKey(dayKey(new Date()));return Math.round((opDate()-today)/86400000)}
function journey(){const n=signedDaysToOp();if(n>0)return{phase:'Vorbereitung',phaseIndex:0,kicker:`Noch ${n} Tage bis zu deiner OP`,sub:`OP am ${opDate().toLocaleDateString('de-DE',{day:'2-digit',month:'2-digit',year:'numeric'})}`};const since=Math.abs(n);if(since<=14)return{phase:'Mobil werden',phaseIndex:2,kicker:`Tag ${since||1} nach deiner OP`,sub:'Phase 2 · Mobil werden'};if(since<=56)return{phase:'Aufbau',phaseIndex:3,kicker:`${since} Tage nach deiner OP`,sub:'Phase 3 · Kraft & Beweglichkeit'};return{phase:'Aktiv werden',phaseIndex:4,kicker:`${Math.max(1,Math.floor(since/7))} Wochen nach deiner OP`,sub:'Phase 4 · Zurück in den aktiven Alltag'}}
function rotationIndex(date){const diff=Math.floor((new Date(date.getFullYear(),date.getMonth(),date.getDate(),12)-ROTATION_START)/86400000);return Math.floor(diff/7)}
function planFor(date){const d=new Date(date.getFullYear(),date.getMonth(),date.getDate(),12);if(d<PLAN_START)return PRESTART;if(dayKey(d)==='2026-08-16')return START_DAY;const weekNo=Math.max(0,rotationIndex(d));const variant=variants[((weekNo%variants.length)+variants.length)%variants.length];return variant[(d.getDay()+6)%7]}
function exerciseKey(date,i){return `${dayKey(date)}-${planFor(date).id}-${i}`}
function completedFor(date){const p=planFor(date);if(p.rest)return[];return p.items.map((e,i)=>({e,i,key:exerciseKey(date,i)})).filter(x=>!!state.checks[x.key])}
function remaining(date){const p=planFor(date);if(p.rest)return[];return p.items.map((e,i)=>({e,i})).filter(x=>!state.checks[exerciseKey(date,x.i)])}
function planMinutes(p){const m=String(p.time||'').match(/(\d+)/);return m?Number(m[1]):0}
function currentWeekRange(){const s=startOfWeek(addDays(new Date(),view.weekOffset*7));return{start:s,end:addDays(s,6)}}
function goalLabel(){return state.profile.goals.length?state.profile.goals.slice(0,2).join(' · '):'Aktiver Alltag'}
function setVersion(){const v=document.querySelector('.version');if(v)v.textContent=`${APP_VERSION} · Build ${BUILD}`}
function updateClock(){const n=new Date(),d=document.getElementById('todayDate'),t=document.getElementById('todayTime');if(d)d.textContent=n.toLocaleDateString('de-DE',{weekday:'short',day:'2-digit',month:'2-digit'});if(t)t.textContent=n.toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function progress(){return Math.max(0,Math.min(100,((START_WEIGHT-Number(state.weight))/(START_WEIGHT-Number(state.target)))*100))}
function formatDate(d,opts={weekday:'long',day:'2-digit',month:'long'}){return new Date(d).toLocaleDateString('de-DE',opts)}
function anatomy(target='Hüfte'){const t=target.toLowerCase();let spot={x:86,y:72,rx:13,ry:10};if(t.includes('gesäß'))spot={x:85,y:83,rx:16,ry:11};else if(t.includes('oberschenkel')||t.includes('quad')||t.includes('hamstring'))spot={x:87,y:112,rx:12,ry:25};else if(t.includes('wade'))spot={x:83,y:150,rx:9,ry:21};else if(t.includes('rumpf')||t.includes('brust')||t.includes('rücken'))spot={x:86,y:54,rx:18,ry:22};return `<svg viewBox="0 0 170 190" aria-hidden="true"><circle cx="85" cy="25" r="14" fill="#d6d8d8"/><path d="M69 43Q85 36 101 43L106 96Q85 105 64 96Z" fill="#bfc5c7"/><path d="M72 94L62 162M98 94L108 162" stroke="#bfc5c7" stroke-width="16" stroke-linecap="round"/><path d="M70 55L44 96M100 55L126 96" stroke="#cbd0d2" stroke-width="12" stroke-linecap="round"/><ellipse cx="${spot.x}" cy="${spot.y}" rx="${spot.rx}" ry="${spot.ry}" fill="#f17c20" opacity=".9"/></svg>`}
function mediaHTML(e){if(webImg[e.media]){const [f]=webImg[e.media];return `<img src="${W}${encodeURIComponent(f)}" alt="${esc(e.name)}" loading="lazy">`}return anatomy(e.target)}
function exerciseRow(e,date,i,{compact=false}={}){const done=!!state.checks[exerciseKey(date,i)];return `<div class="exercise-row ${done?'is-done':''}" onclick="openExerciseVideo('${esc(e.name)}')"><div class="exercise-media">${mediaHTML(e)}<span class="play-dot">▶</span></div><div class="exercise-copy"><div class="exercise-top"><strong>${esc(e.name)}</strong><span class="dose">${esc(e.dose)}</span></div><div class="focus-line">${esc(e.target)}</div>${compact?'':`<p>${esc(e.desc)}</p>`}${done?'<span class="done-label">✓ erledigt</span>':''}</div>${done?`<button class="icon-btn" onclick="event.stopPropagation();undoCompleted('${exerciseKey(date,i)}')">↩</button>`:''}</div>`}
function journeyHTML(){const j=journey(),labels=['Vorbereitung','OP','Mobil','Aufbau','Aktiv'];return `<div class="journey"><div class="journey-line"></div>${labels.map((x,i)=>`<div class="journey-step ${i<=j.phaseIndex?'done':''} ${i===j.phaseIndex?'current':''}"><i></i><span>${x}</span></div>`).join('')}</div>`}
function showPage(p){view.page=p;view.workout=null;document.body.classList.remove('workout-open');document.querySelectorAll('.tabbar button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));const c=document.getElementById('content');if(!c)return;if(p==='home')home(c);else if(p==='training')training(c);else if(p==='progress')progressPage(c);else if(p==='calendar')calendarPage(c);else profilePage(c);setVersion();setTimeout(()=>window.prehipCloudDecorate?.(),0)}
function home(c){const d=new Date(),p=planFor(d),left=remaining(d).length,j=journey(),feeling=state.feelings[dayKey(d)];c.innerHTML=`<div class="page home-page"><section class="home-head"><span class="eyebrow">HEUTE · ${esc(j.phase.toUpperCase())}</span><h1>${esc(j.kicker)}</h1><p>${esc(j.sub)} · Ziel: ${esc(goalLabel())}</p>${journeyHTML()}</section><section class="today-card ${p.rest?'rest':''}"><div class="today-card-head"><div class="activity-icon">${p.icon}</div><div><span class="card-kicker">DEIN TRAINING HEUTE</span><h2>${esc(p.title)}</h2><p>${p.rest?esc(p.time):`${esc(p.time)} · ${left} von ${p.items.length} offen`}</p></div></div>${p.rest?`<div class="rest-message">${p.id==='prestart'?'Dein fester Trainingsplan startet am 16.08. Bis dahin: Alltag und schmerzfreie Bewegung.':'Heute ist bewusst komplett trainingsfrei. Erholung gehört zum Plan.'}</div>`:`<button class="primary big" onclick="openPlanDetail('${dayKey(d)}')">${left===p.items.length?'Training starten':left===0?'Training ansehen':'Training fortsetzen'}</button>`}</section><div class="section-head"><h3>Zusätzliche Aktivität</h3><span>optional</span></div><div class="quick-grid"><button onclick="openTraining('Spaziergang')">🚶<span>Spaziergang</span></button><button onclick="openTraining('Radfahren')">🚴<span>Fahrrad</span></button><button onclick="openTraining('Schwimmen')">🏊<span>Schwimmen</span></button></div><section class="feeling-card"><div><span class="card-kicker">TAGESFORM</span><h3>Wie geht es deiner Hüfte heute?</h3></div><div class="moods"><button class="${feeling?.mood==='gut'?'selected':''}" onclick="setFeeling('gut')">🙂<span>Gut</span></button><button class="${feeling?.mood==='mittel'?'selected':''}" onclick="setFeeling('mittel')">😐<span>Mittel</span></button><button class="${feeling?.mood==='schlecht'?'selected':''}" onclick="setFeeling('schlecht')">😣<span>Schlecht</span></button></div></section><div class="section-head"><h3>Diese Woche</h3><button class="text-btn" onclick="showPage('progress')">Fortschritt ›</button></div>${weekStrip()}</div>`}
function weekStrip(){const s=startOfWeek();return `<div class="week-strip">${Array.from({length:7},(_,i)=>{const d=addDays(s,i),p=planFor(d),done=completedFor(d).length,complete=!p.rest&&done===p.items.length;return `<button class="${dayKey(d)===dayKey(new Date())?'today':''} ${complete?'complete':''}" onclick="openPlanDetail('${dayKey(d)}')"><span>${d.toLocaleDateString('de-DE',{weekday:'short'}).slice(0,2)}</span><b>${d.getDate()}</b><i>${p.rest?'–':complete?'✓':'•'}</i></button>`}).join('')}</div>`}
function setFeeling(mood){state.feelings[dayKey(new Date())]={mood,at:new Date().toISOString()};save();home(document.getElementById('content'))}
function training(c){const range=currentWeekRange(),days=Array.from({length:7},(_,i)=>addDays(range.start,i));c.innerHTML=`<div class="page"><section class="screen-head"><span class="eyebrow">TRAINING</span><h1>Dein Trainingsplan</h1><p>Phase · ${esc(journey().phase)}</p></section><div class="week-nav"><button onclick="changeWeek(-1)">‹</button><strong>${formatDate(range.start,{day:'2-digit',month:'short'})} – ${formatDate(range.end,{day:'2-digit',month:'short'})}</strong><button onclick="changeWeek(1)">›</button></div><div class="plan-list">${days.map(d=>dayCard(d)).join('')}</div><div class="info-card"><strong>Wochenrhythmus</strong><p>Der Plan rotiert in drei Varianten: 2× Radfahren, 2× Rudergerät/Oberkörper, 2× Hüft-/Rumpfkraft und 1 kompletter Ruhetag. Tennis bleibt spontan.</p></div></div>`}
function changeWeek(n){view.weekOffset+=n;training(document.getElementById('content'))}
function dayCard(d){const p=planFor(d),done=completedFor(d).length,left=remaining(d).length,isToday=dayKey(d)===dayKey(new Date());return `<details class="plan-day ${isToday?'today':''}" ${isToday?'open':''}><summary><div class="day-badge"><span>${d.toLocaleDateString('de-DE',{weekday:'short'}).slice(0,2)}</span><b>${d.getDate()}</b></div><div class="plan-summary"><strong>${esc(p.short||p.title)}</strong><small>${esc(p.time)}${p.rest?'':` · ${done}/${p.items.length} erledigt`}</small></div><span class="summary-chevron">⌄</span></summary><div class="plan-body">${p.rest?`<div class="rest-message">${p.id==='prestart'?'Noch kein Pflichttraining.':'Kompletter Ruhetag – bewusst keine Pflichtübungen.'}</div>`:`${p.items.map((e,i)=>exerciseRow(e,d,i,{compact:true})).join('')}<button class="secondary full" onclick="openPlanDetail('${dayKey(d)}')">${left===p.items.length?'Training öffnen':left===0?'Details ansehen':'Training fortsetzen'}</button>`}</div></details>`}
function openPlanDetail(key){const d=dateFromKey(key),p=planFor(d);view.selectedDate=key;const done=completedFor(d).length;modal(`<div class="detail-head"><button class="sheet-close" onclick="closeModal()">×</button><span class="eyebrow">${formatDate(d,{weekday:'long',day:'2-digit',month:'long'}).toUpperCase()}</span><h2>${p.icon} ${esc(p.title)}</h2><p>${esc(p.time)}${p.rest?'':` · ${p.items.length} Übungen · ${done} erledigt`}</p></div>${p.rest?`<div class="rest-message large">${p.id==='prestart'?'Der Trainingsplan startet am 16.08.':'Heute bleibt komplett frei.'}</div>`:`<div class="detail-list">${p.items.map((e,i)=>exerciseRow(e,d,i,{compact:false})).join('')}</div><button class="primary big" onclick="closeModal();startWorkout('${key}')">${done?'Training fortsetzen':'Training starten'}</button>`}`,true)}
function startWorkout(key){const d=dateFromKey(key),p=planFor(d);if(p.rest)return;let idx=p.items.findIndex((_,i)=>!state.checks[exerciseKey(d,i)]);if(idx<0)idx=0;view.workout={date:key,index:idx,set:1,startedAt:new Date().toISOString()};document.body.classList.add('workout-open');renderWorkout()}
function renderWorkout(){const w=view.workout;if(!w)return;const c=document.getElementById('content'),d=dateFromKey(w.date),p=planFor(d),e=p.items[w.index],totalSets=parseSets(e.dose),doneCount=completedFor(d).length;c.innerHTML=`<div class="workout-page"><div class="workout-top"><button onclick="exitWorkout()">‹</button><div><span>${doneCount} von ${p.items.length} erledigt</span><div class="workout-progress"><i style="width:${Math.round((doneCount/p.items.length)*100)}%"></i></div></div><button onclick="exitWorkout()">×</button></div><div class="workout-main"><span class="eyebrow">ÜBUNG ${w.index+1} VON ${p.items.length}</span><h1>${esc(e.name)}</h1><div class="workout-media" onclick="openExerciseVideo('${esc(e.name)}')">${mediaHTML(e)}<span>▶ Video</span></div><div class="workout-dose">${esc(e.dose)}</div><div class="focus-pill">${esc(e.target)}</div><p class="workout-desc">${esc(e.desc)}</p><div class="set-card"><div><span>Aktueller Satz</span><strong>${Math.min(w.set,totalSets)} / ${totalSets}</strong></div><button class="primary" onclick="completeSet()">Satz erledigt ✓</button></div><div class="workout-actions"><button onclick="markCurrentExerciseDone()">Übung komplett</button><button onclick="skipExercise()">Überspringen</button></div></div></div>`}
function parseSets(dose){const m=String(dose).match(/^(\d+)\s*[×x]/i);return m?Number(m[1]):1}
function completeSet(){const w=view.workout,d=dateFromKey(w.date),p=planFor(d),e=p.items[w.index],sets=parseSets(e.dose);if(w.set>=sets){markCurrentExerciseDone();return}w.set++;toast(`Satz ${w.set-1} erledigt · kurze Pause`);renderWorkout()}
function markCurrentExerciseDone(){const w=view.workout,d=dateFromKey(w.date),p=planFor(d),i=w.index,key=exerciseKey(d,i);state.checks[key]=true;state.completed=state.completed.filter(x=>x.key!==key);state.completed.push({key,date:w.date,plan:p.title,exercise:p.items[i].name,dose:p.items[i].dose,target:p.items[i].target,completedAt:new Date().toISOString()});save();nextWorkoutExercise()}
function skipExercise(){nextWorkoutExercise(false)}
function nextWorkoutExercise(){const w=view.workout,d=dateFromKey(w.date),p=planFor(d);let next=-1;for(let n=1;n<=p.items.length;n++){const idx=(w.index+n)%p.items.length;if(!state.checks[exerciseKey(d,idx)]){next=idx;break}}if(next<0||completedFor(d).length===p.items.length){finishWorkout();return}w.index=next;w.set=1;renderWorkout()}
function finishWorkout(){const w=view.workout,d=dateFromKey(w.date),p=planFor(d);state.workoutSessions.push({date:w.date,planId:p.id,plan:p.title,minutes:planMinutes(p),startedAt:w.startedAt,completedAt:new Date().toISOString(),feeling:null});save();document.body.classList.remove('workout-open');view.workout=null;modal(`<div class="finish-screen"><div class="finish-icon">✓</div><span class="eyebrow">TRAINING GESCHAFFT</span><h2>${esc(p.title)}</h2><p>${p.items.length}/${p.items.length} Übungen · ca. ${planMinutes(p)} Minuten</p><h3>Wie hat es sich angefühlt?</h3><div class="moods finish"><button onclick="finishFeeling('leicht')">🙂<span>Leicht</span></button><button onclick="finishFeeling('passend')">💪<span>Passend</span></button><button onclick="finishFeeling('anstrengend')">😮‍💨<span>Anstrengend</span></button></div><button class="secondary full" onclick="closeModal();showPage('home')">Fertig</button></div>`,true)}
function finishFeeling(feel){const s=state.workoutSessions[state.workoutSessions.length-1];if(s)s.feeling=feel;save();closeModal();showPage('home')}
function exitWorkout(){document.body.classList.remove('workout-open');view.workout=null;showPage('training')}
function undoCompleted(key){delete state.checks[key];state.completed=state.completed.filter(x=>x.key!==key);save();if(!document.getElementById('modal').classList.contains('hidden')&&view.selectedDate)openPlanDetail(view.selectedDate);else showPage(view.page)}
function weekStats(){const s=startOfWeek(),e=addDays(s,6),inWeek=k=>{const d=dateFromKey(k);return d>=s&&d<=e},planned=state.completed.filter(x=>inWeek(x.date)),sessions=new Set(planned.map(x=>`${x.date}-${x.plan}`)),spontaneous=state.trainings.filter(x=>inWeek(x.date)),mins=state.workoutSessions.filter(x=>inWeek(x.date)).reduce((a,x)=>a+Number(x.minutes||0),0)+spontaneous.reduce((a,x)=>a+Number(x.duration||0),0);return{sessions:sessions.size+spontaneous.length,mins,activities:spontaneous.length}}
function progressPage(c){const w=weekStats(),milestones=getMilestones();c.innerHTML=`<div class="page"><section class="screen-head"><span class="eyebrow">FORTSCHRITT</span><h1>Dein Weg zurück</h1><p>${esc(journey().kicker)}</p></section><div class="metric-grid"><div class="metric"><b>${w.sessions}</b><span>Einheiten diese Woche</span></div><div class="metric"><b>${w.mins}</b><span>Trainingsminuten</span></div><div class="metric"><b>${w.activities}</b><span>Zusatzaktivitäten</span></div></div><div class="section-head"><h3>Deine Woche</h3></div>${weekProgress()}<div class="section-head"><h3>Gewicht</h3><button class="text-btn" onclick="openWeight()">Eintragen ›</button></div>${weightChart()}<div class="section-head"><h3>Meilensteine</h3></div><div class="milestones">${milestones.map(m=>`<div class="milestone ${m.done?'done':''}"><div>${m.done?'🏆':'🔒'}</div><span>${esc(m.label)}</span></div>`).join('')}</div><div class="section-head"><h3>Verlauf</h3><button class="text-btn danger" onclick="clearHistory()">Verlauf löschen</button></div>${historyList()}</div>`}
function weekProgress(){const s=startOfWeek();return `<div class="progress-week">${Array.from({length:7},(_,i)=>{const d=addDays(s,i),p=planFor(d),done=completedFor(d).length,complete=p.rest?false:done===p.items.length;return `<div><span>${d.toLocaleDateString('de-DE',{weekday:'short'}).slice(0,2)}</span><i class="${complete?'complete':p.rest?'rest':''}">${p.rest?'–':complete?'✓':done?'•':'○'}</i></div>`}).join('')}</div>`}
function getMilestones(){const sessions=new Set(state.completed.map(x=>`${x.date}-${x.plan}`)).size+state.trainings.length,mins=state.workoutSessions.reduce((a,x)=>a+Number(x.minutes||0),0)+state.trainings.reduce((a,x)=>a+Number(x.duration||0),0),bike30=state.trainings.some(x=>x.type==='Radfahren'&&Number(x.duration)>=30);return[{label:'Erstes Training geschafft',done:sessions>=1},{label:'5 Trainingseinheiten',done:sessions>=5},{label:'100 Trainingsminuten',done:mins>=100},{label:'30 Minuten Fahrrad',done:bike30},{label:'OP geschafft',done:signedDaysToOp()<=0}]}
function historyList(){const planned=state.completed.map(x=>({kind:'plan',when:x.completedAt||x.date+'T12:00:00',...x})),spontaneous=state.trainings.map((x,index)=>({kind:'spontaneous',when:x.at||x.date+'T12:00:00',idx:index,...x})),rows=[...planned,...spontaneous].sort((a,b)=>String(b.when).localeCompare(String(a.when))).slice(0,20);if(!rows.length)return'<div class="empty-card">Noch keine Aktivitäten gespeichert.</div>';return `<div class="history-list">${rows.map(x=>x.kind==='plan'?`<div class="history-row"><div class="history-icon">✓</div><div><strong>${esc(x.exercise)}</strong><small>${formatDate(dateFromKey(x.date),{day:'2-digit',month:'2-digit',year:'2-digit'})} · ${esc(x.plan)}</small></div><button onclick="undoCompleted('${x.key}')">↩</button></div>`:`<div class="history-row"><div class="history-icon">${x.icon||'＋'}</div><div><strong>${esc(x.type)}</strong><small>${formatDate(dateFromKey(x.date),{day:'2-digit',month:'2-digit',year:'2-digit'})} · ${Number(x.duration)||0} Min.</small></div><button onclick="deleteTraining(${x.idx})">×</button></div>`).join('')}</div>`}
function clearHistory(){if(!confirm('Trainingsverlauf wirklich löschen? Gewicht und Profil bleiben erhalten.'))return;state.trainings=[];state.checks={};state.completed=[];state.workoutSessions=[];save();progressPage(document.getElementById('content'))}
function deleteTraining(i){state.trainings.splice(i,1);save();progressPage(document.getElementById('content'))}
function weightChart(){const data=[...state.weightHistory].sort((a,b)=>a.date.localeCompare(b.date)).slice(-14);if(!data.length)return'';const Wd=320,H=140,l=24,r=10,t=14,b=24,vals=data.map(x=>Number(x.weight)).filter(Number.isFinite),minV=Math.min(Number(state.target),...vals)-.5,maxV=Math.max(Number(state.target),...vals)+.5,x=i=>data.length===1?160:l+i*((Wd-l-r)/(data.length-1)),y=v=>t+(maxV-v)*((H-t-b)/(maxV-minV||1)),pts=data.map((d,i)=>`${x(i)},${y(Number(d.weight))}`).join(' '),targetY=y(Number(state.target));return `<div class="chart-card"><div class="chart-head"><div><strong>${Number(state.weight).toFixed(1)} kg</strong><span>aktuell</span></div><div><strong>${Number(state.target).toFixed(1)} kg</strong><span>Ziel</span></div></div><svg viewBox="0 0 ${Wd} ${H}"><line x1="${l}" y1="${targetY}" x2="${Wd-r}" y2="${targetY}" stroke="#f17c20" stroke-dasharray="4 4"/><polyline points="${pts}" fill="none" stroke="#26343a" stroke-width="2.5"/><text x="${l}" y="${H-5}" font-size="9" fill="#8b9497">${formatDate(dateFromKey(data[0].date),{day:'2-digit',month:'2-digit'})}</text><text x="${Wd-r}" y="${H-5}" text-anchor="end" font-size="9" fill="#8b9497">${formatDate(dateFromKey(data[data.length-1].date),{day:'2-digit',month:'2-digit'})}</text></svg><div class="weight-bar"><i style="width:${progress()}%"></i></div></div>`}
function openWeight(){modal(`<h2>Gewicht eintragen</h2><div class="field"><label>Gewicht in kg</label><input id="w" type="number" step="0.1" value="${Number(state.weight).toFixed(1)}"></div><button class="primary full" onclick="saveWeight()">Speichern</button>`)}
function saveWeight(){const v=Number(document.getElementById('w')?.value);if(Number.isFinite(v)&&v>0){state.weight=v;const k=dayKey(new Date());state.weightHistory=state.weightHistory.filter(x=>x.date!==k);state.weightHistory.push({date:k,weight:v});state.weightHistory.sort((a,b)=>a.date.localeCompare(b.date));save()}closeModal();showPage(view.page)}
function calendarPage(c){const today=new Date(),base=new Date(today.getFullYear(),today.getMonth()+view.calendarOffset,1,12),year=base.getFullYear(),month=base.getMonth(),first=(base.getDay()+6)%7,count=new Date(year,month+1,0).getDate(),cells=[];for(let i=0;i<first;i++)cells.push('<div class="cal-cell muted"></div>');for(let day=1;day<=count;day++){const d=new Date(year,month,day,12),p=planFor(d),isToday=dayKey(d)===dayKey(today),isOp=dayKey(d)===state.profile.opDate,done=completedFor(d).length,hasSpont=state.trainings.some(x=>x.date===dayKey(d));cells.push(`<button class="cal-cell ${isToday?'today':''} ${isOp?'op':''}" onclick="openCalendarDay('${dayKey(d)}')"><b>${day}</b><div class="cal-dots">${p.rest?'':`<i class="plan ${done===p.items.length?'done':''}"></i>`}${hasSpont?'<i class="activity"></i>':''}${isOp?'<i class="opdot"></i>':''}</div></button>`)}c.innerHTML=`<div class="page"><section class="screen-head"><span class="eyebrow">KALENDER</span><h1>Dein OP-Fahrplan</h1><p>Training, Aktivität und wichtige Termine.</p></section><div class="calendar-card"><div class="calendar-head"><button onclick="changeMonth(-1)">‹</button><strong>${base.toLocaleDateString('de-DE',{month:'long',year:'numeric'})}</strong><button onclick="changeMonth(1)">›</button></div><div class="calendar-weekdays">${['Mo','Di','Mi','Do','Fr','Sa','So'].map(x=>`<span>${x}</span>`).join('')}</div><div class="calendar-grid">${cells.join('')}</div></div><div class="legend"><span><i class="plan"></i>Training</span><span><i class="activity"></i>Aktivität</span><span><i class="opdot"></i>OP</span></div><div class="section-head"><h3>Besondere Termine</h3><button class="text-btn" onclick="openAppointment()">+ Termin</button></div><div class="appointment-list"><div class="appointment op"><span>🏥</span><div><strong>Hüft-OP</strong><small>${formatDate(opDate(),{weekday:'long',day:'2-digit',month:'long',year:'numeric'})}</small></div></div>${state.appointments.map((a,i)=>`<div class="appointment"><span>📌</span><div><strong>${esc(a.title)}</strong><small>${formatDate(dateFromKey(a.date),{weekday:'short',day:'2-digit',month:'long',year:'numeric'})}</small></div><button onclick="deleteAppointment(${i})">×</button></div>`).join('')}</div></div>`}
function changeMonth(n){view.calendarOffset+=n;calendarPage(document.getElementById('content'))}
function openCalendarDay(key){const d=dateFromKey(key),p=planFor(d),done=completedFor(d).length,extras=state.trainings.filter(x=>x.date===key),feel=state.feelings[key];modal(`<div class="detail-head"><button class="sheet-close" onclick="closeModal()">×</button><span class="eyebrow">${formatDate(d,{weekday:'long',day:'2-digit',month:'long'}).toUpperCase()}</span><h2>${dayKey(d)===state.profile.opDate?'🏥 Hüft-OP':`${p.icon} ${esc(p.title)}`}</h2><p>${p.rest?esc(p.time):`${done}/${p.items.length} Übungen erledigt`}</p></div>${!p.rest?`<button class="secondary full" onclick="closeModal();openPlanDetail('${key}')">Training ansehen</button>`:''}${extras.map(x=>`<div class="mini-row"><span>${x.icon||'＋'}</span><div><strong>${esc(x.type)}</strong><small>${Number(x.duration)||0} Minuten</small></div></div>`).join('')}${feel?`<div class="mini-row"><span>${feel.mood==='gut'?'🙂':feel.mood==='mittel'?'😐':'😣'}</span><div><strong>Tagesform: ${esc(feel.mood)}</strong></div></div>`:''}`,true)}
function openAppointment(){modal(`<h2>Termin hinzufügen</h2><div class="field"><label>Titel</label><input id="appt-title" value="Reha"></div><div class="field"><label>Datum</label><input id="appt-date" type="date"></div><button class="primary full" onclick="saveAppointment()">Speichern</button>`)}
function saveAppointment(){const title=document.getElementById('appt-title')?.value.trim(),date=document.getElementById('appt-date')?.value;if(title&&date){state.appointments.push({title,date});save()}closeModal();showPage('calendar')}
function deleteAppointment(i){state.appointments.splice(i,1);save();calendarPage(document.getElementById('content'))}
function profilePage(c){c.innerHTML=`<div class="page"><section class="screen-head"><span class="eyebrow">PROFIL</span><h1>Mein Weg</h1><p>Diese Angaben bestimmen deine persönliche Ansicht.</p></section><div class="profile-hero"><div><span class="card-kicker">HÜFT-OP</span><h2>${formatDate(opDate(),{day:'2-digit',month:'long',year:'numeric'})}</h2><p>${esc(journey().kicker)}</p></div><button class="small-btn" onclick="openProfileEdit('op')">Ändern</button></div><div class="profile-section"><div class="profile-row" onclick="openProfileEdit('goals')"><div><span>Ziele</span><strong>${esc(goalLabel())}</strong></div><b>›</b></div><div class="profile-row" onclick="openProfileEdit('level')"><div><span>Aktivitätsniveau</span><strong>${esc(state.profile.activityLevel)}</strong></div><b>›</b></div><div class="profile-row" onclick="openProfileEdit('days')"><div><span>Trainingstage</span><strong>${trainingDaysText()}</strong></div><b>›</b></div><div class="profile-row" onclick="openProfileEdit('equipment')"><div><span>Equipment</span><strong>${esc(state.profile.equipment.join(' · ')||'Keines')}</strong></div><b>›</b></div></div><div id="prehip-cloud-card"></div><div class="section-head"><h3>Einstellungen</h3></div><div class="profile-section"><div class="profile-row" onclick="openWeight()"><div><span>Gewicht</span><strong>${Number(state.weight).toFixed(1)} kg · Ziel ${Number(state.target).toFixed(1)} kg</strong></div><b>›</b></div><div class="profile-row" onclick="restartOnboarding()"><div><span>Onboarding</span><strong>Erneut durchspielen</strong></div><b>›</b></div></div><div class="dev-box"><span>${APP_VERSION} · Build ${BUILD}</span><button onclick="resetDevData()">Entwicklungsdaten zurücksetzen</button></div></div>`}
function trainingDaysText(){const names=['So','Mo','Di','Mi','Do','Fr','Sa'];return state.profile.trainingDays.slice().sort((a,b)=>((a+6)%7)-((b+6)%7)).map(x=>names[x]).join(' · ')}
function openProfileEdit(type){if(type==='op')return modal(`<h2>OP-Datum</h2><div class="field"><label>Datum</label><input id="profile-op" type="date" value="${state.profile.opDate}"></div><button class="primary full" onclick="saveProfileOp()">Speichern</button>`);if(type==='level')return modal(`<h2>Aktivitätsniveau</h2><div class="choice-list">${['Wenig aktiv','Aktiv','Sportlich'].map(x=>`<button class="choice ${state.profile.activityLevel===x?'selected':''}" onclick="state.profile.activityLevel='${x}';save();closeModal();showPage('profile')">${x}</button>`).join('')}</div>`);if(type==='goals')return multiEdit('Ziele',['Aktiver Alltag','Radfahren','Schwimmen','Wandern','Fitness','Tennis','Skifahren'],'goals');if(type==='equipment')return multiEdit('Equipment',['Theraband','Kurzhanteln','Fahrrad','Rudergerät','Fitnessstudio'],'equipment');if(type==='days')return editDays()}
function saveProfileOp(){const v=document.getElementById('profile-op')?.value;if(v)state.profile.opDate=v;save();closeModal();showPage('profile')}
function multiEdit(title,options,field){modal(`<h2>${title}</h2><div class="chip-select" id="multi-edit">${options.map(x=>`<button data-value="${esc(x)}" class="${state.profile[field].includes(x)?'selected':''}" onclick="this.classList.toggle('selected')">${x}</button>`).join('')}</div><button class="primary full" onclick="saveMulti('${field}')">Speichern</button>`)}
function saveMulti(field){state.profile[field]=[...document.querySelectorAll('#multi-edit button.selected')].map(b=>b.dataset.value);save();closeModal();showPage('profile')}
function editDays(){const days=[['Mo',1],['Di',2],['Mi',3],['Do',4],['Fr',5],['Sa',6],['So',0]];modal(`<h2>Bevorzugte Trainingstage</h2><div class="day-select" id="day-edit">${days.map(([n,v])=>`<button data-value="${v}" class="${state.profile.trainingDays.includes(v)?'selected':''}" onclick="this.classList.toggle('selected')">${n}</button>`).join('')}</div><p class="hint">Der aktuelle V1-Plan behält seinen vorsichtigen Wochenrhythmus; die Auswahl wird für die nächste Plan-Individualisierung gespeichert.</p><button class="primary full" onclick="saveDays()">Speichern</button>`)}
function saveDays(){state.profile.trainingDays=[...document.querySelectorAll('#day-edit button.selected')].map(b=>Number(b.dataset.value));save();closeModal();showPage('profile')}
function resetDevData(){if(!confirm('Alle Entwicklungsdaten wirklich zurücksetzen?'))return;state=JSON.parse(JSON.stringify(state0));state.weightHistory=[{date:dayKey(new Date()),weight:START_WEIGHT}];save();view.onboardingStep=0;view.onboardingDraft=null;renderOnboarding()}
function openTraining(type='Radfahren'){const opts=activities.map(a=>`<option ${a[1]===type?'selected':''}>${a[1]}</option>`).join('');modal(`<h2>Aktivität eintragen</h2><div class="field"><label>Aktivität</label><select id="t">${opts}</select></div><div class="field"><label>Dauer in Minuten</label><input id="d" type="number" value="30" min="1"></div><div class="field"><label>Intensität · 1–10</label><input id="i" type="number" value="5" min="1" max="10"></div><button class="primary full" onclick="saveTraining()">Speichern</button>`)}
function saveTraining(){const t=document.getElementById('t')?.value,d=Number(document.getElementById('d')?.value),i=Number(document.getElementById('i')?.value),a=activities.find(x=>x[1]===t);if(t&&Number.isFinite(d)){state.trainings.push({date:dayKey(new Date()),type:t,icon:a?a[0]:'＋',duration:d,intensity:i||5,at:new Date().toISOString()});save()}closeModal();showPage('home')}
function openExerciseVideo(name){document.getElementById('exercise-video-pop')?.remove();const id=videos[name],m=document.createElement('div');m.id='exercise-video-pop';m.className='video-pop';m.innerHTML=`<div class="video-sheet"><div class="video-head"><strong>${esc(name)}</strong><button onclick="document.getElementById('exercise-video-pop').remove()">×</button></div>${id?`<div class="video-frame"><iframe src="https://www.youtube-nocookie.com/embed/${id}?rel=0&playsinline=1" allowfullscreen></iframe></div>`:`<div class="video-empty"><p>Für diese Übung ist noch kein festes Video hinterlegt.</p><a href="https://www.youtube.com/results?search_query=${encodeURIComponent(name+' Übung')}" target="_blank" rel="noopener">Auf YouTube suchen</a></div>`}</div>`;document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m)m.remove()})}
function modal(h,large=false){const m=document.getElementById('modal');m.innerHTML=`<div class="sheet ${large?'large':''}">${h}${large?'':'<button class="cancel" onclick="closeModal()">Abbrechen</button>'}</div>`;m.classList.remove('hidden')}
function closeModal(){document.getElementById('modal')?.classList.add('hidden')}
function toast(text){let t=document.getElementById('toast');if(!t){t=document.createElement('div');t.id='toast';document.body.appendChild(t)}t.textContent=text;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),1600)}
function restartOnboarding(){state.profile.onboardingDone=false;save();view.onboardingStep=0;view.onboardingDraft=null;renderOnboarding()}
function onboardingDraft(){if(!view.onboardingDraft)view.onboardingDraft=JSON.parse(JSON.stringify(state.profile));return view.onboardingDraft}
function renderOnboarding(){document.body.classList.add('onboarding-open');const c=document.getElementById('content'),d=onboardingDraft(),s=view.onboardingStep,total=5;document.querySelector('.tabbar').style.display='none';let body='';if(s===0)body=`<span class="eyebrow">SCHRITT 1 VON ${total}</span><h1>Wann ist deine OP?</h1><p>Damit richten wir Countdown, Phasen und Kalender auf deinen persönlichen Weg aus.</p><div class="onboard-date"><span>🏥</span><input id="ob-op" type="date" value="${d.opDate||DEFAULT_OP_DATE}"></div>`;if(s===1)body=`<span class="eyebrow">SCHRITT 2 VON ${total}</span><h1>Was möchtest du wieder können?</h1><p>Mehrfachauswahl möglich.</p>${onboardChips(['Aktiver Alltag','Radfahren','Schwimmen','Wandern','Fitness','Tennis','Skifahren'],d.goals,'ob-goal')}`;if(s===2)body=`<span class="eyebrow">SCHRITT 3 VON ${total}</span><h1>Wie aktiv bist du aktuell?</h1><p>Damit können wir den Einstieg später passender dosieren.</p><div class="choice-list" id="ob-level">${['Wenig aktiv','Aktiv','Sportlich'].map(x=>`<button data-value="${x}" class="choice ${d.activityLevel===x?'selected':''}" onclick="selectSingle(this)">${x}</button>`).join('')}</div>`;if(s===3)body=`<span class="eyebrow">SCHRITT 4 VON ${total}</span><h1>Was steht dir zur Verfügung?</h1><p>Wir zeigen später bevorzugt Übungen mit deinem Equipment.</p>${onboardChips(['Theraband','Kurzhanteln','Fahrrad','Rudergerät','Fitnessstudio'],d.equipment,'ob-equipment')}`;if(s===4)body=`<span class="eyebrow">SCHRITT 5 VON ${total}</span><h1>Wann trainierst du am liebsten?</h1><p>Wähle deine bevorzugten Tage. Der aktuelle Hüftplan behält mindestens einen kompletten Ruhetag.</p><div class="day-select" id="ob-days">${[['Mo',1],['Di',2],['Mi',3],['Do',4],['Fr',5],['Sa',6],['So',0]].map(([n,v])=>`<button data-value="${v}" class="${d.trainingDays.includes(v)?'selected':''}" onclick="this.classList.toggle('selected')">${n}</button>`).join('')}</div>`;c.innerHTML=`<div class="onboarding"><div class="onboard-brand"><img src="assets/prehip-logo.svg" alt="preHIP"><span>${APP_VERSION}</span></div><div class="onboard-progress"><i style="width:${((s+1)/total)*100}%"></i></div><div class="onboard-body">${body}</div><div class="onboard-footer">${s>0?'<button class="secondary" onclick="onboardBack()">Zurück</button>':'<button class="secondary ghost" onclick="skipOnboarding()">Überspringen</button>'}<button class="primary" onclick="onboardNext()">${s===total-1?'Plan erstellen':'Weiter'}</button></div></div>`}
function onboardChips(options,selected,id){return `<div class="chip-select onboard" id="${id}">${options.map(x=>`<button data-value="${x}" class="${selected.includes(x)?'selected':''}" onclick="this.classList.toggle('selected')">${x}</button>`).join('')}</div>`}
function selectSingle(btn){btn.parentElement.querySelectorAll('button').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected')}
function persistOnboardStep(){const d=onboardingDraft(),s=view.onboardingStep;if(s===0){const v=document.getElementById('ob-op')?.value;if(v)d.opDate=v}if(s===1)d.goals=[...document.querySelectorAll('#ob-goal button.selected')].map(b=>b.dataset.value);if(s===2)d.activityLevel=document.querySelector('#ob-level button.selected')?.dataset.value||d.activityLevel;if(s===3)d.equipment=[...document.querySelectorAll('#ob-equipment button.selected')].map(b=>b.dataset.value);if(s===4)d.trainingDays=[...document.querySelectorAll('#ob-days button.selected')].map(b=>Number(b.dataset.value))}
function onboardNext(){persistOnboardStep();if(view.onboardingStep<4){view.onboardingStep++;renderOnboarding();return}const d=onboardingDraft();state.profile={...state.profile,...d,onboardingDone:true};save();document.body.classList.remove('onboarding-open');document.querySelector('.tabbar').style.display='grid';view.onboardingDraft=null;view.onboardingStep=0;modal(`<div class="finish-screen"><div class="finish-icon">✓</div><span class="eyebrow">DEIN PLAN IST BEREIT</span><h2>${esc(journey().kicker)}</h2><p>${esc(journey().phase)} · ${esc(goalLabel())}</p><button class="primary full" onclick="closeModal();showPage('home')">Heute ansehen</button></div>`,true)}
function onboardBack(){persistOnboardStep();view.onboardingStep=Math.max(0,view.onboardingStep-1);renderOnboarding()}
function skipOnboarding(){state.profile.onboardingDone=true;save();document.body.classList.remove('onboarding-open');document.querySelector('.tabbar').style.display='grid';showPage('home')}
function init(){setVersion();updateClock();setInterval(updateClock,1000);save();if(!state.profile.onboardingDone)renderOnboarding();else showPage('home')}
init();